import { execSync, type ExecSyncOptions } from "child_process";
import { EventEmitter } from "events";

/**
 * Git Manager
 *
 * Generator가 코드를 생성한 후:
 *   1. 자동 커밋 (기능 단위)
 *   2. 기능별 브랜치 관리
 *   3. diff 정보 제공 (UI용)
 *
 * 전제: 사용자가 지정한 workingDir에 git repo가 존재
 */
export class GitManager extends EventEmitter {
  private workingDir: string;

  constructor(workingDir: string) {
    super();
    this.workingDir = workingDir;
  }

  private exec(cmd: string, throwOnError = false): string {
    try {
      return execSync(cmd, {
        cwd: this.workingDir,
        encoding: "utf-8",
        timeout: 15000,
        shell: true,
        windowsHide: true,
      }).trim();
    } catch (err: any) {
      if (throwOnError) throw err;
      return "";
    }
  }

  /** Git이 초기화되어 있는지 확인 */
  isGitRepo(): boolean {
    return this.exec("git rev-parse --is-inside-work-tree") === "true";
  }

  /** Git repo 초기화 (없으면) */
  init(): boolean {
    if (this.isGitRepo()) return true;
    this.exec("git init", true);
    this.exec('git add -A && git commit -m "Initial commit (WorkTool)" --allow-empty');
    return true;
  }

  /** 현재 브랜치 이름 */
  getCurrentBranch(): string {
    return this.exec("git branch --show-current") || "main";
  }

  /** 기능별 브랜치 생성 + 전환 */
  createFeatureBranch(featureName: string): string {
    const safeName = featureName
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 40);

    const branchName = `feature/${safeName}`;

    // 이미 존재하면 전환만
    const exists = this.exec(`git branch --list "${branchName}"`);
    if (exists) {
      this.exec(`git checkout "${branchName}"`);
    } else {
      this.exec(`git checkout -b "${branchName}"`);
    }

    return branchName;
  }

  /** main 브랜치로 복귀 */
  checkoutMain(): void {
    const main = this.exec("git branch --list main") ? "main" : "master";
    this.exec(`git checkout ${main}`);
  }

  /** 자동 커밋 (Generator 완료 후) */
  autoCommit(featureName: string, changeSummary: string): CommitResult {
    const status = this.getStatus();
    if (!status.hasChanges) {
      return { success: true, hash: "", message: "No changes to commit" };
    }

    // 모든 변경사항 스테이지
    this.exec("git add -A");

    // 커밋 메시지 생성
    const message = `feat: ${featureName}\n\n${changeSummary}\n\nGenerated by WorkTool AI Agent`;

    try {
      this.exec(`git commit -m "${message.replace(/"/g, '\\"')}"`, true);
      const hash = this.exec("git rev-parse --short HEAD");

      this.emit("commit", { hash, featureName, changeSummary });
      return { success: true, hash, message: `Committed: ${hash}` };
    } catch (err: any) {
      return { success: false, hash: "", message: `Commit failed: ${err.message}` };
    }
  }

  /** 현재 상태 */
  getStatus(): GitStatus {
    const statusOutput = this.exec("git status --porcelain");
    const lines = statusOutput.split("\n").filter((l) => l.trim());

    const added = lines.filter((l) => l.startsWith("?") || l.startsWith("A")).length;
    const modified = lines.filter((l) => l.startsWith("M") || l.startsWith(" M")).length;
    const deleted = lines.filter((l) => l.startsWith("D") || l.startsWith(" D")).length;

    return {
      branch: this.getCurrentBranch(),
      hasChanges: lines.length > 0,
      added,
      modified,
      deleted,
      totalChanges: lines.length,
    };
  }

  /** diff 가져오기 (UI 표시용) */
  getDiff(staged = false): string {
    return this.exec(staged ? "git diff --cached --stat" : "git diff --stat");
  }

  /** 최근 커밋 로그 */
  getRecentCommits(count: number = 10): CommitLog[] {
    const log = this.exec(`git log --oneline -${count} --format="%h|%s|%cr"`);
    if (!log) return [];

    return log.split("\n").filter(Boolean).map((line) => {
      const [hash, message, relativeTime] = line.split("|");
      return { hash, message, relativeTime };
    });
  }

  /** 기능 브랜치를 main에 머지 */
  mergeFeature(branchName: string): boolean {
    try {
      this.checkoutMain();
      this.exec(`git merge "${branchName}" --no-ff -m "Merge ${branchName}"`, true);
      return true;
    } catch {
      return false;
    }
  }
}

export interface CommitResult {
  success: boolean;
  hash: string;
  message: string;
}

export interface GitStatus {
  branch: string;
  hasChanges: boolean;
  added: number;
  modified: number;
  deleted: number;
  totalChanges: number;
}

export interface CommitLog {
  hash: string;
  message: string;
  relativeTime: string;
}
